on:
  workflow_dispatch:

name: Sync Submodule

env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sync-submodule:
    name: Sync Submodule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull all submodule
        run: git submodule update --init --recursive

      - name: Setup Git
        run: |
          git config user.name '${{secrets.MAINTAINER_NAME}}'
          git config user.email '${{secrets.MAINTAINER_EMAIL}}'
      
      - name: Create new branch
        run: git checkout -b submodule-sync-${{ github.sha }}

      - name: Sync submodule
        run: |
          git submodule update --remote --merge
      
      - name: Create branch
        run: |
          git add .
          git commit -m "Sync submodules - Updated submodules" || echo "No changes to commit"
          git push origin submodule-sync-${{ github.sha }}

  test:
    needs: sync_submodules  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        uses: ./.github/actions/test.yml